# Generated by Django 5.2.6 on 2025-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='组件名称')),
                ('widget_type', models.CharField(choices=[('chart', '图表'), ('metric', '指标卡'), ('table', '表格'), ('list', '列表')], max_length=20, verbose_name='组件类型')),
                ('config', models.JSONField(verbose_name='组件配置')),
                ('position_x', models.IntegerField(default=0, verbose_name='X坐标')),
                ('position_y', models.IntegerField(default=0, verbose_name='Y坐标')),
                ('width', models.IntegerField(default=4, verbose_name='宽度')),
                ('height', models.IntegerField(default=3, verbose_name='高度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仪表板组件',
                'verbose_name_plural': '仪表板组件',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(default='overview', max_length=50, verbose_name='默认视图')),
                ('theme', models.CharField(default='light', max_length=20, verbose_name='主题')),
                ('language', models.CharField(default='zh-cn', max_length=10, verbose_name='语言')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='启用通知')),
                ('auto_refresh_interval', models.IntegerField(default=30, verbose_name='自动刷新间隔（秒）')),
            ],
            options={
                'verbose_name': '用户偏好设置',
                'verbose_name_plural': '用户偏好设置',
            },
        ),
    ]
