# Generated by Django 5.2.6 on 2025-09-26 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='申请理由')),
                ('skills', models.JSONField(default=list, verbose_name='技能清单')),
                ('experience', models.TextField(blank=True, verbose_name='相关经验')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='作品集链接')),
                ('expected_commitment', models.CharField(blank=True, max_length=100, verbose_name='可投入时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='申请状态')),
                ('review_notes', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成员申请',
                'verbose_name_plural': '成员申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='招募标题')),
                ('description', models.TextField(verbose_name='招募描述')),
                ('required_skills', models.JSONField(default=list, verbose_name='所需技能')),
                ('skill_level_required', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家')], default='intermediate', max_length=20, verbose_name='技能等级要求')),
                ('positions_needed', models.IntegerField(default=1, verbose_name='招募人数')),
                ('positions_filled', models.IntegerField(default=0, verbose_name='已招募人数')),
                ('work_type', models.CharField(choices=[('full_time', '全职'), ('part_time', '兼职'), ('contract', '合同工'), ('volunteer', '志愿者')], default='part_time', max_length=50, verbose_name='工作类型')),
                ('expected_commitment', models.CharField(blank=True, help_text='如：每周10小时', max_length=100, verbose_name='预期投入时间')),
                ('salary_range', models.CharField(blank=True, max_length=100, verbose_name='薪资范围')),
                ('equity_percentage_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='最小股份比例')),
                ('equity_percentage_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='最大股份比例')),
                ('status', models.CharField(choices=[('open', '开放招募'), ('paused', '暂停招募'), ('closed', '结束招募')], default='open', max_length=20, verbose_name='招募状态')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成员招募',
                'verbose_name_plural': '成员招募',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('project_type', models.CharField(choices=[('research', '研发项目'), ('academic', '学术项目'), ('design', '设计项目'), ('innovation', '创新实验'), ('development', '开发项目'), ('other', '其他')], default='other', max_length=20, verbose_name='项目类型')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('pending', '待审核'), ('suspended', '暂停')], default='active', max_length=20, verbose_name='项目状态')),
                ('tags', models.JSONField(blank=True, default=list, help_text='项目标签', verbose_name='项目标签')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='项目进度')),
                ('total_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总投资额')),
                ('valuation', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='项目估值')),
                ('funding_rounds', models.IntegerField(default=0, verbose_name='融资轮次')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开展示')),
                ('invite_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='邀请码')),
                ('invite_code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='邀请码过期时间')),
                ('invite_code_enabled', models.BooleanField(default=True, verbose_name='是否启用邀请码')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('project_created', '项目创建'), ('project_updated', '项目更新'), ('project_deleted', '项目删除'), ('project_archived', '项目归档'), ('project_restored', '项目恢复'), ('member_joined', '成员加入'), ('member_left', '成员离开'), ('member_role_changed', '成员角色变更'), ('member_invited', '邀请成员'), ('member_removed', '移除成员'), ('member_permission_changed', '成员权限变更'), ('comment_added', '评论添加'), ('comment_updated', '评论更新'), ('comment_deleted', '评论删除'), ('message_sent', '发送消息'), ('rating_created', '评分创建'), ('rating_completed', '评分完成'), ('evaluation_started', '评估开始'), ('evaluation_completed', '评估完成'), ('points_awarded', '积分奖励'), ('points_deducted', '积分扣除'), ('milestone_reached', '里程碑达成'), ('milestone_created', '里程碑创建'), ('milestone_updated', '里程碑更新'), ('status_changed', '状态变更'), ('progress_updated', '进度更新'), ('vote_created', '创建投票'), ('vote_participated', '参与投票'), ('vote_completed', '投票完成'), ('decision_made', '做出决策'), ('investment_made', '投资操作'), ('revenue_recorded', '收益记录'), ('expense_recorded', '支出记录'), ('valuation_updated', '估值更新'), ('backup_created', '创建备份'), ('settings_changed', '设置变更'), ('permission_granted', '授予权限'), ('permission_revoked', '撤销权限'), ('other', '其他操作')], max_length=50, verbose_name='日志类型')),
                ('title', models.CharField(max_length=200, verbose_name='日志标题')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('action_method', models.CharField(blank=True, help_text='如：POST, PUT, DELETE, GET等', max_length=50, verbose_name='操作方法')),
                ('action_function', models.CharField(blank=True, help_text='如：创建任务、更新项目、分配成员等', max_length=100, verbose_name='操作功能')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='变更内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '项目日志',
                'verbose_name_plural': '项目日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '项目负责人'), ('admin', '管理员'), ('member', '普通成员'), ('observer', '观察者')], default='member', max_length=20, verbose_name='角色')),
                ('contribution_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='贡献比例')),
                ('equity_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='股份比例')),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='投资金额')),
                ('contribution_description', models.TextField(blank=True, verbose_name='贡献描述')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
            },
        ),
        migrations.CreateModel(
            name='ProjectRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_type', models.CharField(choices=[('investment', '投资收入'), ('sales', '销售收入'), ('service', '服务收入'), ('licensing', '授权收入'), ('grant', '资助资金'), ('other', '其他收入')], max_length=20, verbose_name='收益类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收益金额')),
                ('description', models.TextField(verbose_name='收益描述')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='收益来源')),
                ('associated_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='相关成本')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='净收益')),
                ('revenue_date', models.DateField(verbose_name='收益日期')),
                ('is_distributed', models.BooleanField(default=False, verbose_name='是否已分配')),
                ('distribution_date', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目收益',
                'verbose_name_plural': '项目收益',
                'ordering': ['-revenue_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='分配金额')),
                ('equity_percentage_at_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='分配时股份比例')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='支付方式')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='支付凭证号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
            ],
            options={
                'verbose_name': '收益分配',
                'verbose_name_plural': '收益分配',
                'ordering': ['-created_at'],
            },
        ),
    ]
