# Generated by Django 5.0.6 on 2025-08-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_project_completed_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_rounds',
            field=models.IntegerField(default=1, verbose_name='融资轮次'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='equity_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='股份比例'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='投资金额'),
        ),
    ]
