# Generated by Django 5.0.6 on 2025-08-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_funding_rounds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_rounds',
            field=models.IntegerField(default=0, verbose_name='融资轮次'),
        ),
    ]
