# Generated by Django 5.0.6 on 2025-08-09 23:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_funding_rounds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='招募标题')),
                ('description', models.TextField(verbose_name='招募描述')),
                ('required_skills', models.JSONField(default=list, verbose_name='所需技能')),
                ('skill_level_required', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家')], default='intermediate', max_length=20, verbose_name='技能等级要求')),
                ('positions_needed', models.IntegerField(default=1, verbose_name='招募人数')),
                ('positions_filled', models.IntegerField(default=0, verbose_name='已招募人数')),
                ('work_type', models.CharField(choices=[('full_time', '全职'), ('part_time', '兼职'), ('contract', '合同工'), ('volunteer', '志愿者')], default='part_time', max_length=50, verbose_name='工作类型')),
                ('expected_commitment', models.CharField(blank=True, help_text='如：每周10小时', max_length=100, verbose_name='预期投入时间')),
                ('salary_range', models.CharField(blank=True, max_length=100, verbose_name='薪资范围')),
                ('equity_percentage_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='最小股份比例')),
                ('equity_percentage_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='最大股份比例')),
                ('status', models.CharField(choices=[('open', '开放招募'), ('paused', '暂停招募'), ('closed', '结束招募')], default='open', max_length=20, verbose_name='招募状态')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '成员招募',
                'verbose_name_plural': '成员招募',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_type', models.CharField(choices=[('investment', '投资收入'), ('sales', '销售收入'), ('service', '服务收入'), ('licensing', '授权收入'), ('grant', '资助资金'), ('other', '其他收入')], max_length=20, verbose_name='收益类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收益金额')),
                ('description', models.TextField(verbose_name='收益描述')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='收益来源')),
                ('associated_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='相关成本')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='净收益')),
                ('revenue_date', models.DateField(verbose_name='收益日期')),
                ('is_distributed', models.BooleanField(default=False, verbose_name='是否已分配')),
                ('distribution_date', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='projects.project', verbose_name='项目')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '项目收益',
                'verbose_name_plural': '项目收益',
                'ordering': ['-revenue_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_members', models.IntegerField(default=2, verbose_name='最大成员数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='projects.task', verbose_name='任务')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_task_teams', to=settings.AUTH_USER_MODEL, verbose_name='团队负责人')),
            ],
            options={
                'verbose_name': '任务团队',
                'verbose_name_plural': '任务团队',
            },
        ),
        migrations.CreateModel(
            name='TaskTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '团队负责人'), ('member', '团队成员'), ('reviewer', '评审员')], default='member', max_length=20, verbose_name='角色')),
                ('work_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='团队内工作量分配权重', max_digits=3, verbose_name='工作权重')),
                ('peer_evaluation_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='同行评分')),
                ('self_evaluation_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='自评分数')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.taskteam', verbose_name='任务团队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '任务团队成员',
                'verbose_name_plural': '任务团队成员',
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddField(
            model_name='taskteam',
            name='members',
            field=models.ManyToManyField(related_name='task_teams', through='projects.TaskTeamMembership', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        ),
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='申请理由')),
                ('skills', models.JSONField(default=list, verbose_name='技能清单')),
                ('experience', models.TextField(blank=True, verbose_name='相关经验')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='作品集链接')),
                ('expected_commitment', models.CharField(blank=True, max_length=100, verbose_name='可投入时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='申请状态')),
                ('review_notes', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.memberrecruitment', verbose_name='招募信息')),
            ],
            options={
                'verbose_name': '成员申请',
                'verbose_name_plural': '成员申请',
                'ordering': ['-created_at'],
                'unique_together': {('recruitment', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='RevenueDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='分配金额')),
                ('equity_percentage_at_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='分配时股份比例')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='支付方式')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='支付凭证号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectmembership', verbose_name='成员关系')),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='projects.projectrevenue', verbose_name='项目收益')),
            ],
            options={
                'verbose_name': '收益分配',
                'verbose_name_plural': '收益分配',
                'ordering': ['-created_at'],
                'unique_together': {('revenue', 'member')},
            },
        ),
    ]
