# Generated by Django 5.0.6 on 2025-08-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_memberrecruitment_projectrevenue_taskteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开展示'),
        ),
    ]
