# Generated by Django 5.2.6 on 2025-09-26 07:30

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('is_available_for_claim', models.BooleanField(default=False, verbose_name='是否可被领取')),
                ('allow_claim_without_login', models.BooleanField(default=False, verbose_name='允许未登录领取')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开任务')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='完成日期')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='完成进度')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='预估工时')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='实际工时')),
                ('system_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='系统分')),
                ('function_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='功分')),
                ('time_coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='时效系数')),
                ('weight_coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1.0'))], verbose_name='项目权重系数')),
                ('tags', models.TextField(blank=True, help_text='标签，用逗号分隔', verbose_name='任务标签')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='任务分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='角色权重')),
                ('system_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='系统分')),
                ('function_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='功分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务分配',
                'verbose_name_plural': '任务分配',
                'db_table': 'tasks_taskassignment',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/%d/', verbose_name='附件')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[('document', '文档'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('archive', '压缩包'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '任务附件',
                'verbose_name_plural': '任务附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务评论',
                'verbose_name_plural': '任务评论',
            },
        ),
        migrations.CreateModel(
            name='TaskContributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('work_quality', '工作质量'), ('work_efficiency', '工作效率'), ('team_collaboration', '团队协作'), ('innovation', '创新程度'), ('problem_solving', '问题解决'), ('communication', '沟通交流'), ('leadership', '领导能力'), ('technical_skill', '技术能力')], max_length=30, verbose_name='贡献类型')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='贡献分数')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='权重')),
                ('description', models.TextField(blank=True, verbose_name='贡献描述')),
                ('evidence', models.TextField(blank=True, verbose_name='支撑证据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务贡献记录',
                'verbose_name_plural': '任务贡献记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('function', '功分评估'), ('system', '系统分调整')], default='function', max_length=20, verbose_name='评分类型')),
                ('evaluation_mode', models.CharField(choices=[('peer', '同行评分'), ('self', '自我评分'), ('leader', '领导评分')], default='peer', max_length=20, verbose_name='评估模式')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='总评分')),
                ('criteria_scores', models.JSONField(default=dict, verbose_name='各维度评分')),
                ('comment', models.TextField(verbose_name='评分理由')),
                ('improvement_suggestions', models.TextField(blank=True, verbose_name='改进建议')),
                ('work_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='工作量权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务评估',
                'verbose_name_plural': '任务评估',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='评估会话名称')),
                ('description', models.TextField(blank=True, verbose_name='评估说明')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('criteria_config', models.JSONField(default=dict, verbose_name='评分标准配置')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='评分截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务评估会话',
                'verbose_name_plural': '任务评估会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '创建任务'), ('assigned', '分配任务'), ('status_changed', '状态变更'), ('priority_changed', '优先级变更'), ('updated', '更新任务'), ('progress_updated', '进度更新'), ('deadline_changed', '截止日期变更'), ('comment_added', '添加评论'), ('attachment_uploaded', '上传附件'), ('attachment_deleted', '删除附件'), ('evaluation_added', '添加评估'), ('completed', '任务完成'), ('cancelled', '取消任务')], max_length=30, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='原值')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='新值')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTeamMeritCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_method', models.CharField(choices=[('single', '单人参与'), ('duo', '双人协作'), ('small_group', '小组协作'), ('large_group', '大组协作')], max_length=20, verbose_name='计算方法')),
                ('participant_count', models.IntegerField(verbose_name='参与人数')),
                ('total_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总贡献值')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='计算时间')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='是否已确定')),
                ('calculation_summary', models.JSONField(default=dict, verbose_name='计算摘要')),
            ],
            options={
                'verbose_name': '任务团队功分计算',
                'verbose_name_plural': '任务团队功分计算',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTeamMeritResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='贡献值')),
                ('merit_points', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='功分')),
                ('weight_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='权重因子')),
                ('adjustment_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='调整因子')),
            ],
            options={
                'verbose_name': '团队功分计算结果',
                'verbose_name_plural': '团队功分计算结果',
                'ordering': ['-merit_points'],
            },
        ),
        migrations.CreateModel(
            name='TaskUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('progress', '进度更新'), ('bug', '问题反馈'), ('solution', '解决方案'), ('note', '工作笔记'), ('milestone', '里程碑')], default='note', max_length=20, verbose_name='日志类型')),
                ('title', models.CharField(max_length=200, verbose_name='日志标题')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='更新进度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户任务日志',
                'verbose_name_plural': '用户任务日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskUserLogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_log_attachments/%Y/%m/%d/', verbose_name='附件')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '用户任务日志附件',
                'verbose_name_plural': '用户任务日志附件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
