# Generated by Django 5.0.6 on 2025-08-10 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_memberrecruitment_projectrevenue_taskteam_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='关联项目'),
            preserve_default=False,
        ),
    ]
