# Generated by Django 5.2.6 on 2025-09-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='taskcontributionrecord',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_records', to=settings.AUTH_USER_MODEL, verbose_name='贡献者'),
        ),
        migrations.AddField(
            model_name='taskcontributionrecord',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_contributions', to=settings.AUTH_USER_MODEL, verbose_name='记录者'),
        ),
        migrations.AddField(
            model_name='taskcontributionrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_records', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='taskevaluation',
            name='evaluated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_evaluations_received', to=settings.AUTH_USER_MODEL, verbose_name='被评分者'),
        ),
        migrations.AddField(
            model_name='taskevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='评分者'),
        ),
        migrations.AddField(
            model_name='taskevaluation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='taskevaluationsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='taskevaluationsession',
            name='participants',
            field=models.ManyToManyField(related_name='evaluation_sessions_participated', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
        migrations.AddField(
            model_name='taskevaluationsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='taskevaluationsession',
            name='selected_tasks',
            field=models.ManyToManyField(to='tasks.task', verbose_name='待评估任务'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='taskteammeritcalculation',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merit_calculation', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='taskteammeritresult',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_results', to='tasks.taskteammeritcalculation', verbose_name='计算记录'),
        ),
        migrations.AddField(
            model_name='taskteammeritresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_results', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
        migrations.AddField(
            model_name='taskuserlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='taskuserlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_user_logs', to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AddField(
            model_name='taskuserlogattachment',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskuserlog', verbose_name='日志'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'user')},
        ),
        migrations.AddIndex(
            model_name='taskcontributionrecord',
            index=models.Index(fields=['task', 'contributor'], name='tasks_taskc_task_id_0381d4_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcontributionrecord',
            index=models.Index(fields=['contribution_type', '-score'], name='tasks_taskc_contrib_015c23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcontributionrecord',
            unique_together={('task', 'contributor', 'recorder', 'contribution_type')},
        ),
        migrations.AlterUniqueTogether(
            name='taskevaluation',
            unique_together={('task', 'evaluator', 'evaluated_user')},
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task', '-created_at'], name='tasks_taskl_task_id_f65401_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['user', '-created_at'], name='tasks_taskl_user_id_de226f_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['action', '-created_at'], name='tasks_taskl_action_5a5065_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskteammeritresult',
            unique_together={('calculation', 'participant')},
        ),
        migrations.AddIndex(
            model_name='taskuserlog',
            index=models.Index(fields=['task', '-created_at'], name='tasks_tasku_task_id_86f621_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserlog',
            index=models.Index(fields=['user', '-created_at'], name='tasks_tasku_user_id_9e3e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserlog',
            index=models.Index(fields=['log_type', '-created_at'], name='tasks_tasku_log_typ_f5e7c7_idx'),
        ),
    ]
