# Generated by Django 5.0.6 on 2025-08-11 02:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='实际工时'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='任务分类'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='预估工时'),
        ),
        migrations.AddField(
            model_name='task',
            name='function_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='功分'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='完成进度'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AddField(
            model_name='task',
            name='system_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='系统分'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.TextField(blank=True, help_text='标签，用逗号分隔', verbose_name='任务标签'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_coefficient',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='时效系数'),
        ),
        migrations.CreateModel(
            name='TaskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('function', '功分评估'), ('system', '系统分调整')], default='function', max_length=20, verbose_name='评分类型')),
                ('evaluation_mode', models.CharField(choices=[('peer', '同行评分'), ('self', '自我评分'), ('leader', '领导评分')], default='peer', max_length=20, verbose_name='评估模式')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='总评分')),
                ('criteria_scores', models.JSONField(default=dict, verbose_name='各维度评分')),
                ('comment', models.TextField(verbose_name='评分理由')),
                ('improvement_suggestions', models.TextField(blank=True, verbose_name='改进建议')),
                ('work_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='工作量权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('evaluated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_evaluations_received', to=settings.AUTH_USER_MODEL, verbose_name='被评分者')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='评分者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务评估',
                'verbose_name_plural': '任务评估',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'evaluator', 'evaluated_user')},
            },
        ),
    ]
