# Generated by Django 5.0.6 on 2025-08-11 05:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_memberrecruitment_projectrevenue_taskteam_and_more'),
        ('tasks', '0003_task_actual_hours_task_category_task_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='评估会话名称')),
                ('description', models.TextField(blank=True, verbose_name='评估说明')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('criteria_config', models.JSONField(default=dict, verbose_name='评分标准配置')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='评分截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('participants', models.ManyToManyField(related_name='evaluation_sessions_participated', to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='关联项目')),
                ('selected_tasks', models.ManyToManyField(to='tasks.task', verbose_name='待评估任务')),
            ],
            options={
                'verbose_name': '任务评估会话',
                'verbose_name_plural': '任务评估会话',
                'ordering': ['-created_at'],
            },
        ),
    ]
