# Generated by Django 5.0.6 on 2025-08-12 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskevaluationsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '任务附件', 'verbose_name_plural': '任务附件'},
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='description',
            field=models.TextField(blank=True, verbose_name='文件描述'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='文件大小(字节)'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='file_type',
            field=models.CharField(choices=[('document', '文档'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('archive', '压缩包'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='task_attachments/%Y/%m/%d/', verbose_name='附件'),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '创建任务'), ('assigned', '分配任务'), ('status_changed', '状态变更'), ('priority_changed', '优先级变更'), ('updated', '更新任务'), ('progress_updated', '进度更新'), ('deadline_changed', '截止日期变更'), ('comment_added', '添加评论'), ('attachment_uploaded', '上传附件'), ('attachment_deleted', '删除附件'), ('evaluation_added', '添加评估'), ('completed', '任务完成'), ('cancelled', '取消任务')], max_length=30, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='原值')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='新值')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='tasks_taskl_task_id_f65401_idx'), models.Index(fields=['user', '-created_at'], name='tasks_taskl_user_id_de226f_idx'), models.Index(fields=['action', '-created_at'], name='tasks_taskl_action_5a5065_idx')],
            },
        ),
    ]
