# Generated by Django 5.0.6 on 2025-08-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_taskattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_available_for_claim',
            field=models.BooleanField(default=False, verbose_name='是否可被领取'),
        ),
    ]
