# Generated by Django 5.0.6 on 2025-08-21 00:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_is_available_for_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('progress', '进度更新'), ('bug', '问题反馈'), ('solution', '解决方案'), ('note', '工作笔记'), ('milestone', '里程碑')], default='note', max_length=20, verbose_name='日志类型')),
                ('title', models.CharField(max_length=200, verbose_name='日志标题')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='更新进度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to='tasks.task', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_user_logs', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '用户任务日志',
                'verbose_name_plural': '用户任务日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskUserLogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_log_attachments/%Y/%m/%d/', verbose_name='附件')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskuserlog', verbose_name='日志')),
            ],
            options={
                'verbose_name': '用户任务日志附件',
                'verbose_name_plural': '用户任务日志附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskuserlog',
            index=models.Index(fields=['task', '-created_at'], name='tasks_tasku_task_id_86f621_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserlog',
            index=models.Index(fields=['user', '-created_at'], name='tasks_tasku_user_id_9e3e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserlog',
            index=models.Index(fields=['log_type', '-created_at'], name='tasks_tasku_log_typ_f5e7c7_idx'),
        ),
    ]
