# Generated by Django 5.0.6 on 2025-08-21 03:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskuserlog_taskuserlogattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTeamMeritCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_method', models.CharField(choices=[('single', '单人参与'), ('duo', '双人协作'), ('small_group', '小组协作'), ('large_group', '大组协作')], max_length=20, verbose_name='计算方法')),
                ('participant_count', models.IntegerField(verbose_name='参与人数')),
                ('total_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总贡献值')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='计算时间')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='是否已确定')),
                ('calculation_summary', models.JSONField(default=dict, verbose_name='计算摘要')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merit_calculation', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务团队功分计算',
                'verbose_name_plural': '任务团队功分计算',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskContributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('work_quality', '工作质量'), ('work_efficiency', '工作效率'), ('team_collaboration', '团队协作'), ('innovation', '创新程度'), ('problem_solving', '问题解决'), ('communication', '沟通交流'), ('leadership', '领导能力'), ('technical_skill', '技术能力')], max_length=30, verbose_name='贡献类型')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='贡献分数')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='权重')),
                ('description', models.TextField(blank=True, verbose_name='贡献描述')),
                ('evidence', models.TextField(blank=True, verbose_name='支撑证据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_records', to=settings.AUTH_USER_MODEL, verbose_name='贡献者')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_contributions', to=settings.AUTH_USER_MODEL, verbose_name='记录者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_records', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务贡献记录',
                'verbose_name_plural': '任务贡献记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'contributor'], name='tasks_taskc_task_id_0381d4_idx'), models.Index(fields=['contribution_type', '-score'], name='tasks_taskc_contrib_015c23_idx')],
                'unique_together': {('task', 'contributor', 'recorder', 'contribution_type')},
            },
        ),
        migrations.CreateModel(
            name='TaskTeamMeritResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='贡献值')),
                ('merit_points', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='功分')),
                ('weight_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='权重因子')),
                ('adjustment_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='调整因子')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_results', to='tasks.taskteammeritcalculation', verbose_name='计算记录')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_results', to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '团队功分计算结果',
                'verbose_name_plural': '团队功分计算结果',
                'ordering': ['-merit_points'],
                'unique_together': {('calculation', 'participant')},
            },
        ),
    ]
