# Generated by Django 5.2.6 on 2025-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('earned', '获得积分'), ('spent', '消费积分'), ('bonus', '奖励积分'), ('penalty', '扣除积分'), ('transfer_in', '转入积分'), ('transfer_out', '转出积分')], max_length=20, verbose_name='记录类型')),
                ('amount', models.IntegerField(verbose_name='积分数量')),
                ('description', models.TextField(verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
            },
        ),
        migrations.CreateModel(
            name='PointsRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField(verbose_name='消费积分')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('delivered', '已发放'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('delivery_info', models.JSONField(blank=True, null=True, verbose_name='配送信息')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name': '积分兑换',
                'verbose_name_plural': '积分兑换',
            },
        ),
        migrations.CreateModel(
            name='PointsReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='奖励名称')),
                ('description', models.TextField(verbose_name='奖励描述')),
                ('points_required', models.IntegerField(verbose_name='所需积分')),
                ('reward_type', models.CharField(max_length=50, verbose_name='奖励类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/', verbose_name='奖励图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '积分奖励',
                'verbose_name_plural': '积分奖励',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='积分数量')),
                ('message', models.TextField(blank=True, verbose_name='转账留言')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='交易ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '积分转账',
                'verbose_name_plural': '积分转账',
            },
        ),
    ]
