# Generated by Django 5.0.6 on 2025-08-05 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_options_project_completed_tasks_and_more'),
        ('voting', '0002_alter_contributionevaluation_evaluated_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='奖励名称')),
                ('description', models.TextField(verbose_name='奖励描述')),
                ('points_required', models.IntegerField(verbose_name='所需积分')),
                ('reward_type', models.CharField(max_length=50, verbose_name='奖励类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/', verbose_name='奖励图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '积分奖励',
                'verbose_name_plural': '积分奖励',
            },
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('earned', '获得积分'), ('spent', '消费积分'), ('bonus', '奖励积分'), ('penalty', '扣除积分'), ('transfer_in', '转入积分'), ('transfer_out', '转出积分')], max_length=20, verbose_name='记录类型')),
                ('amount', models.IntegerField(verbose_name='积分数量')),
                ('description', models.TextField(verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='相关项目')),
                ('related_vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.vote', verbose_name='相关投票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
            },
        ),
        migrations.CreateModel(
            name='PointsRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField(verbose_name='消费积分')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('delivered', '已发放'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('delivery_info', models.JSONField(blank=True, null=True, verbose_name='配送信息')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pointsreward', verbose_name='奖励')),
            ],
            options={
                'verbose_name': '积分兑换',
                'verbose_name_plural': '积分兑换',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='积分数量')),
                ('message', models.TextField(blank=True, verbose_name='转账留言')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='交易ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_sent', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_received', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '积分转账',
                'verbose_name_plural': '积分转账',
            },
        ),
    ]
