# Generated by Django 5.2.6 on 2025-09-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0002_initial'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsrecord',
            name='related_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.vote', verbose_name='相关投票'),
        ),
        migrations.AddField(
            model_name='pointsrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='pointsredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='pointsredemption',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pointsreward', verbose_name='奖励'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_sent', to=settings.AUTH_USER_MODEL, verbose_name='发送人'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_received', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
    ]
