# Generated by Django 5.2.6 on 2025-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('individual', '个人财务报表'), ('project', '项目财务报表')], max_length=20, verbose_name='报表类型')),
                ('data_source', models.CharField(choices=[('manual', '手工输入'), ('calculated', '系统计算')], default='manual', max_length=20, verbose_name='数据来源')),
                ('total_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='总资产')),
                ('current_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='流动资产')),
                ('fixed_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='固定资产')),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='总负债')),
                ('equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='所有者权益')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='营业收入')),
                ('costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='营业成本')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='毛利润')),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='营业费用')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='净利润')),
                ('operating_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='经营活动现金流')),
                ('investing_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='投资活动现金流')),
                ('financing_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='筹资活动现金流')),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='净现金流')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='是否授权公开')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='授权时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '财务报表',
                'verbose_name_plural': '财务报表',
            },
        ),
        migrations.CreateModel(
            name='ShareholderEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='投资金额')),
                ('equity_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='股权比例')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '股权记录',
                'verbose_name_plural': '股权记录',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('transaction_type', models.CharField(choices=[('vote_payment', '投票支付'), ('investment', '投资'), ('dividend', '分红'), ('refund', '退款'), ('deposit', '充值'), ('withdrawal', '提现')], max_length=20, verbose_name='交易类型')),
                ('description', models.TextField(blank=True, verbose_name='交易描述')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='交易ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
            },
        ),
    ]
