# Generated by Django 5.2.6 on 2025-09-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('projects', '0001_initial'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='voting_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_reports', to='voting.votinground', verbose_name='投票轮次'),
        ),
        migrations.AddField(
            model_name='shareholderequity',
            name='target_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='目标项目'),
        ),
        migrations.AddField(
            model_name='shareholderequity',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equity_holders', to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
        ),
        migrations.AddField(
            model_name='shareholderequity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='股东'),
        ),
        migrations.AddField(
            model_name='shareholderequity',
            name='voting_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_holdings', to='voting.votinground', verbose_name='投票轮次'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.vote', verbose_name='相关投票'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='接收项目'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
        migrations.AlterUniqueTogether(
            name='financialreport',
            unique_together={('project', 'voting_round'), ('user', 'voting_round')},
        ),
        migrations.AlterUniqueTogether(
            name='shareholderequity',
            unique_together={('user', 'target_project', 'voting_round'), ('user', 'target_user', 'voting_round')},
        ),
    ]
