# Generated by Django 5.0.6 on 2025-08-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
        ('voting', '0003_alter_contributionevaluation_voting_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='voting_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_reports', to='voting.votinground', verbose_name='投票轮次'),
        ),
        migrations.AlterField(
            model_name='shareholderequity',
            name='voting_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_holdings', to='voting.votinground', verbose_name='投票轮次'),
        ),
    ]
