# Generated by Django 5.0.6 on 2025-08-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_financialreport_voting_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='data_source',
            field=models.CharField(choices=[('manual', '手工输入'), ('calculated', '系统计算')], default='manual', max_length=20, verbose_name='数据来源'),
        ),
    ]
