# Generated by Django 5.2.6 on 2025-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('report_type', models.CharField(choices=[('user_performance', '用户绩效分析'), ('project_progress', '项目进度分析'), ('voting_statistics', '投票统计分析'), ('financial_overview', '财务概览分析')], max_length=20, verbose_name='报告类型')),
                ('data', models.JSONField(verbose_name='分析数据')),
                ('summary', models.TextField(verbose_name='分析摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告',
            },
        ),
        migrations.CreateModel(
            name='DataMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('description', models.TextField(blank=True, verbose_name='指标描述')),
                ('metric_type', models.CharField(max_length=50, verbose_name='指标类型')),
                ('value', models.JSONField(verbose_name='指标值')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '数据指标',
                'verbose_name_plural': '数据指标',
            },
        ),
    ]
