# Generated by Django 5.0.6 on 2025-08-05 06:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_options_project_completed_tasks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标准名称')),
                ('description', models.TextField(verbose_name='标准描述')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评价标准',
                'verbose_name_plural': '评价标准',
            },
        ),
        migrations.CreateModel(
            name='MeritRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='评价轮次名称')),
                ('description', models.TextField(blank=True, verbose_name='评价轮次描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '功分互评轮次',
                'verbose_name_plural': '功分互评轮次',
            },
        ),
        migrations.CreateModel(
            name='ContributionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='贡献分数')),
                ('comment', models.TextField(blank=True, verbose_name='评价意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('evaluated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_evaluations_received', to=settings.AUTH_USER_MODEL, verbose_name='被评价人')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_contribution_evaluations', to='projects.project', verbose_name='项目')),
                ('merit_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merit.meritround', verbose_name='评价轮次')),
            ],
            options={
                'verbose_name': '贡献评价',
                'verbose_name_plural': '贡献评价',
                'unique_together': {('evaluator', 'evaluated_user', 'project', 'merit_round')},
            },
        ),
        migrations.CreateModel(
            name='DetailedEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='分数')),
                ('comment', models.TextField(blank=True, verbose_name='详细意见')),
                ('base_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_evaluations', to='merit.contributionevaluation', verbose_name='基础评价')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merit.meritcriteria', verbose_name='评价标准')),
            ],
            options={
                'verbose_name': '详细评价',
                'verbose_name_plural': '详细评价',
                'unique_together': {('base_evaluation', 'criteria')},
            },
        ),
    ]
