# Generated by Django 5.2.6 on 2025-09-26 07:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='贡献分数')),
                ('comment', models.TextField(blank=True, verbose_name='评价意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '贡献评价',
                'verbose_name_plural': '贡献评价',
            },
        ),
        migrations.CreateModel(
            name='DetailedEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='分数')),
                ('comment', models.TextField(blank=True, verbose_name='详细意见')),
            ],
            options={
                'verbose_name': '详细评价',
                'verbose_name_plural': '详细评价',
            },
        ),
        migrations.CreateModel(
            name='MeritCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_system_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='系统分总计')),
                ('total_peer_reviews_received', models.IntegerField(default=0, verbose_name='收到的互评数量')),
                ('average_peer_review_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='互评平均分')),
                ('individual_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='个人获得积分')),
                ('total_team_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='全队总积分')),
                ('function_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='功分得分')),
                ('final_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='最终得分')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='计算时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '功分计算结果',
                'verbose_name_plural': '功分计算结果',
                'ordering': ['-final_score'],
            },
        ),
        migrations.CreateModel(
            name='MeritCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标准名称')),
                ('description', models.TextField(verbose_name='标准描述')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评价标准',
                'verbose_name_plural': '评价标准',
            },
        ),
        migrations.CreateModel(
            name='MeritRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='评价轮次名称')),
                ('description', models.TextField(blank=True, verbose_name='评价轮次描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '功分互评轮次',
                'verbose_name_plural': '功分互评轮次',
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='评分（0-100分）')),
                ('work_quality_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='工作质量评分')),
                ('collaboration_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='团队协作评分')),
                ('efficiency_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='工作效率评分')),
                ('innovation_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='创新程度评分')),
                ('comment', models.TextField(blank=True, verbose_name='评价意见')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='是否匿名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '同行互评',
                'verbose_name_plural': '同行互评',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMeritCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计算名称')),
                ('description', models.TextField(blank=True, verbose_name='计算说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('total_project_value', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='项目总价值（分）')),
                ('calculation_start_date', models.DateTimeField(blank=True, null=True, verbose_name='计算开始时间')),
                ('calculation_end_date', models.DateTimeField(blank=True, null=True, verbose_name='计算结束时间')),
                ('peer_review_deadline', models.DateTimeField(blank=True, null=True, verbose_name='互评截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目功分计算',
                'verbose_name_plural': '项目功分计算',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMeritAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='任务占比（%）')),
                ('role_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)], verbose_name='角色权重系数')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='计划开始日期')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='计划完成日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际完成日期')),
                ('time_coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='时效系数')),
                ('system_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='系统分')),
                ('function_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='功分')),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='总分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务功分分配',
                'verbose_name_plural': '任务功分分配',
                'ordering': ['-total_score'],
            },
        ),
    ]
