# Generated by Django 5.2.6 on 2025-09-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merit', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionevaluation',
            name='evaluated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_evaluations_received', to=settings.AUTH_USER_MODEL, verbose_name='被评价人'),
        ),
        migrations.AddField(
            model_name='contributionevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='评价人'),
        ),
        migrations.AddField(
            model_name='contributionevaluation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_contribution_evaluations', to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='detailedevaluation',
            name='base_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_evaluations', to='merit.contributionevaluation', verbose_name='基础评价'),
        ),
        migrations.AddField(
            model_name='meritcalculationresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_calculation_results', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='detailedevaluation',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merit.meritcriteria', verbose_name='评价标准'),
        ),
        migrations.AddField(
            model_name='contributionevaluation',
            name='merit_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merit.meritround', verbose_name='评价轮次'),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='reviewed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_peer_reviews', to=settings.AUTH_USER_MODEL, verbose_name='被评价人'),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_peer_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价人'),
        ),
        migrations.AddField(
            model_name='projectmeritcalculation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_merit_calculations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='projectmeritcalculation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_calculations', to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='merit.projectmeritcalculation', verbose_name='功分计算'),
        ),
        migrations.AddField(
            model_name='meritcalculationresult',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='merit.projectmeritcalculation', verbose_name='功分计算'),
        ),
        migrations.AddField(
            model_name='taskmeritassignment',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='merit.projectmeritcalculation', verbose_name='功分计算'),
        ),
        migrations.AddField(
            model_name='taskmeritassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_assignments', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='taskmeritassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_merit_assignments', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='detailedevaluation',
            unique_together={('base_evaluation', 'criteria')},
        ),
        migrations.AlterUniqueTogether(
            name='contributionevaluation',
            unique_together={('evaluator', 'evaluated_user', 'project', 'merit_round')},
        ),
        migrations.AlterUniqueTogether(
            name='peerreview',
            unique_together={('calculation', 'reviewer', 'reviewed_user')},
        ),
        migrations.AlterUniqueTogether(
            name='meritcalculationresult',
            unique_together={('calculation', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='taskmeritassignment',
            unique_together={('calculation', 'task', 'user')},
        ),
    ]
