# Generated by Django 5.2.6 on 2025-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('project_created', '项目创建'), ('project_updated', '项目更新'), ('project_deleted', '项目删除'), ('project_archived', '项目归档'), ('project_restored', '项目恢复'), ('member_joined', '成员加入'), ('member_left', '成员离开'), ('member_role_changed', '成员角色变更'), ('member_invited', '邀请成员'), ('member_removed', '移除成员'), ('member_permission_changed', '成员权限变更'), ('file_uploaded', '文件上传'), ('file_deleted', '文件删除'), ('file_downloaded', '文件下载'), ('file_shared', '文件分享'), ('comment_added', '评论添加'), ('comment_updated', '评论更新'), ('comment_deleted', '评论删除'), ('message_sent', '发送消息'), ('rating_created', '评分创建'), ('rating_completed', '评分完成'), ('evaluation_started', '评估开始'), ('evaluation_completed', '评估完成'), ('points_awarded', '积分奖励'), ('points_deducted', '积分扣除'), ('milestone_reached', '里程碑达成'), ('milestone_created', '里程碑创建'), ('milestone_updated', '里程碑更新'), ('status_changed', '状态变更'), ('progress_updated', '进度更新'), ('vote_created', '创建投票'), ('vote_participated', '参与投票'), ('vote_completed', '投票完成'), ('decision_made', '做出决策'), ('investment_made', '投资操作'), ('revenue_recorded', '收益记录'), ('expense_recorded', '支出记录'), ('valuation_updated', '估值更新'), ('backup_created', '创建备份'), ('settings_changed', '设置变更'), ('permission_granted', '授予权限'), ('permission_revoked', '撤销权限'), ('other', '其他操作')], max_length=50, verbose_name='日志类型')),
                ('title', models.CharField(max_length=200, verbose_name='日志标题')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('action_method', models.CharField(blank=True, help_text='如：POST, PUT, DELETE, GET等', max_length=50, verbose_name='操作方法')),
                ('action_function', models.CharField(blank=True, help_text='如：创建任务、更新项目、分配成员等', max_length=100, verbose_name='操作功能')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='变更内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '项目日志',
                'verbose_name_plural': '项目日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10, verbose_name='日志级别')),
                ('log_type', models.CharField(choices=[('system', '系统操作'), ('auth', '认证相关'), ('database', '数据库操作'), ('api', 'API调用'), ('file', '文件操作'), ('email', '邮件发送'), ('other', '其他')], max_length=20, verbose_name='日志类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='请求路径')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('task_created', '任务创建'), ('task_updated', '任务更新'), ('task_deleted', '任务删除'), ('task_completed', '任务完成'), ('task_assigned', '任务分配'), ('task_reassigned', '任务重新分配'), ('task_priority_changed', '任务优先级变更'), ('task_deadline_changed', '任务截止日期变更'), ('task_progress_updated', '任务进度更新'), ('task_status_changed', '任务状态变更'), ('file_uploaded', '文件上传'), ('file_deleted', '文件删除'), ('file_downloaded', '文件下载'), ('file_shared', '文件分享'), ('comment_added', '评论添加'), ('comment_updated', '评论更新'), ('comment_deleted', '评论删除'), ('evaluation_submitted', '评分提交'), ('evaluation_updated', '评分更新'), ('other', '其他操作')], max_length=50, verbose_name='日志类型')),
                ('title', models.CharField(max_length=200, verbose_name='日志标题')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('action_method', models.CharField(blank=True, max_length=50, verbose_name='操作方法')),
                ('action_function', models.CharField(blank=True, max_length=100, verbose_name='操作功能')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='变更内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('work_start', '开始工作'), ('work_pause', '暂停工作'), ('work_resume', '恢复工作'), ('work_complete', '工作完成'), ('progress_update', '进度更新'), ('issue_reported', '问题报告'), ('solution_provided', '解决方案'), ('milestone_reached', '里程碑达成'), ('note_added', '添加备注'), ('other', '其他')], max_length=20, verbose_name='日志类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('work_duration', models.DurationField(blank=True, null=True, verbose_name='工作时长')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='工作地点')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10, verbose_name='优先级')),
                ('is_important', models.BooleanField(default=False, verbose_name='是否重要')),
                ('is_private', models.BooleanField(default=False, verbose_name='是否私有')),
                ('logged_at', models.DateTimeField(verbose_name='日志时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务用户日志',
                'verbose_name_plural': '任务用户日志',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskUserLogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_user_log_attachments/%Y/%m/%d/', verbose_name='附件')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('document', '文档'), ('video', '视频'), ('audio', '音频'), ('archive', '压缩包'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '任务用户日志附件',
                'verbose_name_plural': '任务用户日志附件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
