# Generated by Django 5.2.6 on 2025-09-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlog',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_system_logs_about', to=settings.AUTH_USER_MODEL, verbose_name='相关用户'),
        ),
        migrations.AddField(
            model_name='projectlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_system_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='相关用户'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_system_logs_about', to=settings.AUTH_USER_MODEL, verbose_name='相关用户'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_system_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='taskuserlog',
            name='related_users',
            field=models.ManyToManyField(blank=True, related_name='related_task_system_user_logs', to=settings.AUTH_USER_MODEL, verbose_name='相关用户'),
        ),
        migrations.AddField(
            model_name='taskuserlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_user_logs', to='tasks.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='taskuserlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_system_user_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='taskuserlogattachment',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='logs.taskuserlog', verbose_name='日志'),
        ),
        migrations.AddIndex(
            model_name='projectlog',
            index=models.Index(fields=['project', '-created_at'], name='logs_projec_project_2c1bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectlog',
            index=models.Index(fields=['user', '-created_at'], name='logs_projec_user_id_304043_idx'),
        ),
        migrations.AddIndex(
            model_name='projectlog',
            index=models.Index(fields=['log_type', '-created_at'], name='logs_projec_log_typ_238109_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['level', '-created_at'], name='logs_system_level_c7c9de_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['log_type', '-created_at'], name='logs_system_log_typ_e2461c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', '-created_at'], name='logs_system_user_id_21ef4d_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task', '-created_at'], name='logs_tasklo_task_id_781240_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['user', '-created_at'], name='logs_tasklo_user_id_c5def3_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['log_type', '-created_at'], name='logs_tasklo_log_typ_fda042_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserlog',
            index=models.Index(fields=['task', 'user', '-logged_at'], name='logs_taskus_task_id_c65d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserlog',
            index=models.Index(fields=['user', '-logged_at'], name='logs_taskus_user_id_68e71b_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserlog',
            index=models.Index(fields=['log_type', '-logged_at'], name='logs_taskus_log_typ_525177_idx'),
        ),
    ]
