# Generated by Django 5.2.6 on 2025-09-26 07:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='投票轮次名称')),
                ('description', models.TextField(blank=True, verbose_name='投票轮次描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
                ('is_self_evaluation_open', models.BooleanField(default=False, verbose_name='是否开放自评')),
                ('max_self_investment', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='最大自投金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '投票轮次',
                'verbose_name_plural': '投票轮次',
            },
        ),
        migrations.CreateModel(
            name='RatingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='评分主题')),
                ('description', models.TextField(blank=True, verbose_name='评分说明')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已结束')], default='active', max_length=20, verbose_name='状态')),
                ('total_points', models.IntegerField(default=100, verbose_name='总分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_rating_sessions', to='projects.project', verbose_name='项目')),
                ('selected_members', models.ManyToManyField(related_name='voting_rating_sessions', to=settings.AUTH_USER_MODEL, verbose_name='参与成员')),
            ],
            options={
                'verbose_name': '评分活动',
                'verbose_name_plural': '评分活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='评分')),
                ('remark', models.TextField(blank=True, verbose_name='评分备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='评分者')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_received_ratings', to=settings.AUTH_USER_MODEL, verbose_name='被评分者')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_records', to='voting.ratingsession', verbose_name='评分活动')),
            ],
            options={
                'verbose_name': '评分记录',
                'verbose_name_plural': '评分记录',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'rater', 'target')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='投票金额')),
                ('vote_type', models.CharField(choices=[('individual', '个人投票'), ('project', '项目投票'), ('self', '自投')], max_length=20, verbose_name='投票类型')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='支付交易ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('target_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='目标项目')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL, verbose_name='投票人')),
                ('voting_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votinground', verbose_name='投票轮次')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票',
                'unique_together': {('voter', 'target_project'), ('voter', 'target_user')},
            },
        ),
        migrations.CreateModel(
            name='SelfEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', '个人'), ('project', '项目')], max_length=20, verbose_name='实体类型')),
                ('entity_id', models.PositiveIntegerField(verbose_name='实体ID')),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='投资金额')),
                ('previous_valuation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='投资前估值')),
                ('new_valuation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='投资后估值')),
                ('previous_equity_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='投资前股份比例')),
                ('new_equity_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='投资后股份比例')),
                ('dilution_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='稀释比例')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否已批准')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='投资人')),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_evaluations', to='voting.votinground', verbose_name='投票轮次')),
            ],
            options={
                'verbose_name': '自评增资',
                'verbose_name_plural': '自评增资',
                'unique_together': {('entity_type', 'entity_id', 'voting_round', 'investor')},
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', '个人'), ('project', '项目')], max_length=20, verbose_name='实体类型')),
                ('entity_id', models.PositiveIntegerField(verbose_name='实体ID')),
                ('total_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总资产')),
                ('current_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='流动资产')),
                ('fixed_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='固定资产')),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总负债')),
                ('equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='所有者权益')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='营业收入')),
                ('costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='营业成本')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='毛利润')),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='营业费用')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='净利润')),
                ('operating_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='经营现金流')),
                ('investing_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='投资现金流')),
                ('financing_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='筹资现金流')),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='净现金流')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='是否授权公开')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='授权时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_reports', to='voting.votinground', verbose_name='投票轮次')),
            ],
            options={
                'verbose_name': '财务报表',
                'verbose_name_plural': '财务报表',
                'unique_together': {('entity_type', 'entity_id', 'voting_round')},
            },
        ),
        migrations.CreateModel(
            name='EquityCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', '个人'), ('project', '项目')], max_length=20, verbose_name='实体类型')),
                ('entity_id', models.PositiveIntegerField(verbose_name='实体ID')),
                ('total_investment_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='收到的总投资')),
                ('total_investment_made', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='对外投资总额')),
                ('investment_equity_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='投资股份比例')),
                ('total_contribution_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='总贡献评分')),
                ('contribution_equity_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='贡献股份比例')),
                ('final_equity_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='最终股份比例')),
                ('calculation_details', models.JSONField(default=dict, verbose_name='计算详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_calculations', to='voting.votinground', verbose_name='投票轮次')),
            ],
            options={
                'verbose_name': '股份计算',
                'verbose_name_plural': '股份计算',
                'unique_together': {('entity_type', 'entity_id', 'voting_round')},
            },
        ),
        migrations.CreateModel(
            name='ContributionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='贡献分数')),
                ('comment', models.TextField(blank=True, verbose_name='评价意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('evaluated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_evaluations_received', to=settings.AUTH_USER_MODEL, verbose_name='被评价人')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_contribution_evaluations', to='projects.project', verbose_name='项目')),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_evaluations', to='voting.votinground', verbose_name='投票轮次')),
            ],
            options={
                'verbose_name': '贡献评价',
                'verbose_name_plural': '贡献评价',
                'unique_together': {('evaluator', 'evaluated_user', 'project', 'voting_round')},
            },
        ),
    ]
