# Generated by Django 5.0.6 on 2025-08-04 02:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='投票轮次名称')),
                ('description', models.TextField(blank=True, verbose_name='投票轮次描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
                ('is_self_evaluation_open', models.BooleanField(default=False, verbose_name='是否开放自评')),
                ('max_self_investment', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='最大自投金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '投票轮次',
                'verbose_name_plural': '投票轮次',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)], verbose_name='投票金额')),
                ('vote_type', models.CharField(choices=[('individual', '个人投票'), ('project', '项目投票'), ('self', '自投')], max_length=20, verbose_name='投票类型')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='支付交易ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('target_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='目标项目')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL, verbose_name='投票人')),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votinground', verbose_name='投票轮次')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票',
                'unique_together': {('voter', 'target_project', 'voting_round'), ('voter', 'target_user', 'voting_round')},
            },
        ),
        migrations.CreateModel(
            name='ContributionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='贡献分数')),
                ('comment', models.TextField(blank=True, verbose_name='评价意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('evaluated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL, verbose_name='被评价人')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='项目')),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votinground', verbose_name='投票轮次')),
            ],
            options={
                'verbose_name': '贡献评价',
                'verbose_name_plural': '贡献评价',
                'unique_together': {('evaluator', 'evaluated_user', 'project', 'voting_round')},
            },
        ),
    ]
