# Generated by Django 5.0.6 on 2025-08-05 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_project_completed_tasks_and_more'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionevaluation',
            name='evaluated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_evaluations_received', to=settings.AUTH_USER_MODEL, verbose_name='被评价人'),
        ),
        migrations.AlterField(
            model_name='contributionevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='评价人'),
        ),
        migrations.AlterField(
            model_name='contributionevaluation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_contribution_evaluations', to='projects.project', verbose_name='项目'),
        ),
    ]
