# Generated by Django 5.0.6 on 2025-08-06 03:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_contributionevaluation_evaluated_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionevaluation',
            name='voting_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_evaluations', to='voting.votinground', verbose_name='投票轮次'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voting_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votinground', verbose_name='投票轮次'),
        ),
        migrations.CreateModel(
            name='EquityCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', '个人'), ('project', '项目')], max_length=20, verbose_name='实体类型')),
                ('entity_id', models.PositiveIntegerField(verbose_name='实体ID')),
                ('total_investment_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='收到的总投资')),
                ('total_investment_made', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='对外投资总额')),
                ('investment_equity_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='投资股份比例')),
                ('total_contribution_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='总贡献评分')),
                ('contribution_equity_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='贡献股份比例')),
                ('final_equity_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='最终股份比例')),
                ('calculation_details', models.JSONField(default=dict, verbose_name='计算详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_calculations', to='voting.votinground', verbose_name='投票轮次')),
            ],
            options={
                'verbose_name': '股份计算',
                'verbose_name_plural': '股份计算',
                'unique_together': {('entity_type', 'entity_id', 'voting_round')},
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', '个人'), ('project', '项目')], max_length=20, verbose_name='实体类型')),
                ('entity_id', models.PositiveIntegerField(verbose_name='实体ID')),
                ('total_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总资产')),
                ('current_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='流动资产')),
                ('fixed_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='固定资产')),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总负债')),
                ('equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='所有者权益')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='营业收入')),
                ('costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='营业成本')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='毛利润')),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='营业费用')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='净利润')),
                ('operating_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='经营现金流')),
                ('investing_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='投资现金流')),
                ('financing_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='筹资现金流')),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='净现金流')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='是否授权公开')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='授权时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_reports', to='voting.votinground', verbose_name='投票轮次')),
            ],
            options={
                'verbose_name': '财务报表',
                'verbose_name_plural': '财务报表',
                'unique_together': {('entity_type', 'entity_id', 'voting_round')},
            },
        ),
        migrations.CreateModel(
            name='SelfEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', '个人'), ('project', '项目')], max_length=20, verbose_name='实体类型')),
                ('entity_id', models.PositiveIntegerField(verbose_name='实体ID')),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)], verbose_name='投资金额')),
                ('previous_valuation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='投资前估值')),
                ('new_valuation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='投资后估值')),
                ('previous_equity_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='投资前股份比例')),
                ('new_equity_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='投资后股份比例')),
                ('dilution_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='稀释比例')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否已批准')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='投资人')),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_evaluations', to='voting.votinground', verbose_name='投票轮次')),
            ],
            options={
                'verbose_name': '自评增资',
                'verbose_name_plural': '自评增资',
                'unique_together': {('entity_type', 'entity_id', 'voting_round', 'investor')},
            },
        ),
    ]
