# Generated by Django 5.0.6 on 2025-08-06 06:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_contributionevaluation_voting_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfevaluation',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='投资金额'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='投票金额'),
        ),
    ]
